### PR TITLE
UPDATED: Maintenance year

### PR DESCRIPTION
**Pull request by hipio**
It's 2017, not 2016.

### CODE REVIEW

**Comment by Potherca** [comment]
Before merging this PR we should update the `LICENSE` and `README` files as well...

**Comment by hipio** [comment]
@Potherca will fix those with this PR as well. Give me a second or two.

**Comment by hipio** [comment]
This is still pending @Potherca ;)

**Comment by Potherca** [comment]
It must have fallen of my todo list :crying_cat_face:.

Thanks for the ping!

**Pull request merged**
